package com.drkstrinc.pokemon.datatype;

public enum BattleItemUsability {
	NONE, POKEMON_SINGLE_USE, MOVE_SINGLE_USE, STAT_SINGLE_USE, OPPONENT_SINGLE_USE, NO_TARGET_SINGLE_USE,
	POKEMON_MULTIPLE_USE, MOVE_MULTIPLE_USE, STAT_MULTIPLE_USE, OPPONENT_MULTIPLE_USE, NO_TARGET_MULTIPLE_USE
}
